### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by DrakeNn**
Server Status

### CODE REVIEW

**Comment by mrmarktyy** [comment]
@DrakeNn this looks very promising. Have you considered to add support to gather player game statistics like what official site already did ?

**Comment by mrmarktyy** [comment]
Hi @Eureka22, just wondering why there are two gameserver.ini ?

**Comment by fxia22** [comment]
@mrmarktyy Oh because you can run the server from different paths. Actually only one is required. You should use the latest one.

**Comment by mrmarktyy** [comment]
@Eureka22  thanks! I am confused a bit earlier that game server pulled different gameserver.ini when it was started from different paths. Maybe we should use absolute path to resolve config file path?

**Comment by fxia22** [comment]
@mrmarktyy Yeah you can do that.

**Pull request merged**
